version: '3.8'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biznesbadgirlsdb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3360:3360
    networks:
      - biznes-bad-girls

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - biznes-bad-girls

  prestashop:
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PS_INSTALL_AUTO: 0
      DB_SERVER: db
      DB_USER: root
      DB_PASSWD: root
      DB_NAME: biznesbadgirlsdb
      PS_DEV_MODE: 0
      ALLOW_OVERRIDE: 1
      PS_FOLDER_ADMIN: adminPanel
      PS_DOMAIN: localhost:80
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./src:/var/www/html
      - ./src/adminPanel:/var/www/html/adminPanel
      - ./src/modules:/var/www/html/modules
      - ./src/themes:/var/www/html/themes
      - ./src/override:/var/www/html/override
    networks:
      - biznes-bad-girls

networks:
  biznes-bad-girls:
