version: '3'

volumes:
  db-data:

services:
  mysql:
    platform: linux/amd64
    build:
      context: ./mysql/.
      dockerfile: .docker/Dockerfile
    ports:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    deploy:
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
  
  prestashop-git:
    build:
      context: .docker
      dockerfile: .docker/Dockerfile
    environment:
      DISABLE_MAKE: ${DISABLE_MAKE:-1}
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO:-1}
      DB_PASSWD: ${DB_PASSWD:-prestashop}
      DB_NAME: ${DB_NAME:-prestashop}
      DB_SERVER: ${DB_SERVER:-mysql}
      DB_PREFIX: ${DB_PREFIX:-ps_}
      PS_DOMAIN: ${PS_DOMAIN:-localhost:18305}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL:-install-dev}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-dev}
      PS_COUNTRY: ${PS_COUNTRY:-pl}
      PS_LANGUAGE: ${PS_LANGUAGE:-pl}
      PS_DEV_MODE: ${PS_DEV_MODE:-1}
      PS_DEMO_MODE: ${PS_DEMO_MODE:-0}
      PS_HANDLE_DYNAMIC_DOMAIN: ${PS_HANDLE_DYNAMIC_DOMAIN:-1}
      PS_INSTALL_DB: ${PS_INSTALL_DB:-1}
      PS_ENABLE_SSL: ${PS_ENABLE_SSL:-1}
      ADMIN_MAIL: ${ADMIN_MAIL:-s183043@student.pg.edu.pl}
      ADMIN_PASSWD: ${ADMIN_PASSWD:-Had4fcIgjgIMVQrM}
    command: ["/tmp/wait-for-it.sh", "--timeout=60", "--strict", "mysql:3306", "--", "/tmp/docker_run_git.sh"]
    ports:
      - "18305:80"
      - "18306:443"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mysql:mysql
    ports:
      - 18307:80
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=prestashop
