<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDOU9RUJ\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDOU9RUJ/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerDOU9RUJ.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerDOU9RUJ\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerDOU9RUJ\appAppKernelProdContainer([
    'container.build_hash' => 'DOU9RUJ',
    'container.build_id' => '9deb126a',
    'container.build_time' => 1673126074,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDOU9RUJ');
